/angle_control:
  ros__parameters:
    angle_controller_param:
      diff_lpf_time_const:
        seconds: 0.004999999888241291
      kd: 0.03
      ki: 0.02
      kp: 0.2
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    target_angle_deg: 360.0
    use_sim_time: false

